version: "3.8"
services:
  influx1:
    container_name: influx1
    image: influxdb:1.8
    restart: unless-stopped
    environment:
      - TZ="America/Santiago"
    volumes:
      - /home/smartgrid/Escritorio/data/influx1:/var/lib/influxdb
      - ./etc/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./backup:/backup
      - /etc/localtime:/etc/localtime:ro
    command: -config /etc/influxdb/influxdb.conf
    networks:
      - dockerlink
networks:
  dockerlink:
    external:
      name: dockerlink
