apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: netdev-grafana-pvc
  namespace: netdev-rubin-2022
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-2f7a2eb2-d9ce-4f91-bef8-7b96165f7323
