apiVersion: v1
data:
  INFLUXDB_DATABASE: bG9jYWxEQg==
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_PASSWORD: YWRtaW4=
  INFLUXDB_USERNAME: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2022-12-20T20:49:43Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:INFLUXDB_DATABASE: {}
        f:INFLUXDB_HOST: {}
        f:INFLUXDB_PASSWORD: {}
        f:INFLUXDB_USERNAME: {}
      f:type: {}
    manager: agent
    operation: Update
    time: "2022-12-20T20:49:43Z"
  name: influxdb-creds
  namespace: netdev-rubin-2022
  resourceVersion: "157573655"
  uid: 43f4dd10-a144-4c3b-8ed2-9acd48884496
type: Opaque
