apiVersion: v1
data:
  datasources.yaml: "apiVersion: 1\ndatasources:\n- access: proxy\n  database: telegraf\n
    \ isDefault: true\n  name: IT InfluxDB\n  type: influxdb\n  url: http://influxdb.it-influxdb:8086\n
    \ user: ${INFLUXDB_USERNAME}\n  password: ${INFLUXDB_PASSWORD}\n- access: proxy\n
    \ database: _internal\n  isDefault: false\n  name: IT InfluxDB internal\n  type:
    influxdb\n  url: http://influxdb.it-influxdb:8086\n  user: ${INFLUXDB_USERNAME}\n
    \ password: ${INFLUXDB_PASSWORD}\n- name: ruka-prometheus\n  type: prometheus\n
    \ uid: ruka-prometheus\n  url: http://ruka-metrics.dev.lsst.org:9090/\n  access:
    proxy\n  isDefault: false\n  jsonData:\n    timeInterval: 30s\n  \n"
  enabled: |
    false
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth.ldap]
    allow_sign_up = true
    config_file = /etc/grafana/ldap.toml
    enabled = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
  label: |
    grafana_notifier
  plugins: snuids-trafficlights-panel
  searchNamespace: |
    null
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"datasources.yaml":"apiVersion: 1\ndatasources:\n- access: proxy\n  database: telegraf\n  isDefault: true\n  name: IT InfluxDB\n  type: influxdb\n  url: http://influxdb.it-influxdb:8086\n  user: ${INFLUXDB_USERNAME}\n  password: ${INFLUXDB_PASSWORD}\n- access: proxy\n  database: _internal\n  isDefault: false\n  name: IT InfluxDB internal\n  type: influxdb\n  url: http://influxdb.it-influxdb:8086\n  user: ${INFLUXDB_USERNAME}\n  password: ${INFLUXDB_PASSWORD}\n- name: ruka-prometheus\n  type: prometheus\n  uid: ruka-prometheus\n  url: http://ruka-metrics.dev.lsst.org:9090/\n  access: proxy\n  isDefault: false\n  jsonData:\n    timeInterval: 30s\n  \n","enabled":"false\n","grafana.ini":"[analytics]\ncheck_for_updates = true\n[auth.ldap]\nallow_sign_up = true\nconfig_file = /etc/grafana/ldap.toml\nenabled = true\n[grafana_net]\nurl = https://grafana.net\n[log]\nmode = console\n[paths]\ndata = /var/lib/grafana/data\nlogs = /var/log/grafana\nplugins = /var/lib/grafana/plugins\nprovisioning = /etc/grafana/provisioning\n","label":"grafana_notifier\n","plugins":"snuids-trafficlights-panel","searchNamespace":"null\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"grafana","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"7.2.0","helm.sh/chart":"grafana-5.6.12"},"name":"grafana","namespace":"it-grafana"}}
  creationTimestamp: "2022-12-20T19:44:11Z"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.2.0
    helm.sh/chart: grafana-5.6.12
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:datasources.yaml: {}
        f:enabled: {}
        f:grafana.ini: {}
        f:label: {}
        f:plugins: {}
        f:searchNamespace: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
    manager: agent
    operation: Update
    time: "2022-12-20T19:44:11Z"
  name: nd-grafana-cr
  namespace: netdev-rubin-2022
  resourceVersion: "157545253"
  uid: dae952e3-456e-4644-9229-f450466523aa
